### ISSUE TITLE
'global' is not defined. 

### ISSUE THREAD

**Issue by dcjohnston** [adambom/parallel.js#101]
Running into an issue, I followed the examples and have tried messing around with a few things (i.e. using 'self instead of 'global' but to no avail. 

			var job = new Parallel(resourceStore.alertArray, {
				env: {
					'timeQuery': nv,
					'textQuery': $scope.filterQuery,
				},
				envNamespace: 'filterStates'
			}).require({
				fn: listViewFilter, name: 'textFilter'
			}, {
				fn: timeFilter.filter, name: 'timeFilter'
			});

			job.reduce(function(partiallyFilteredArray, currentAlert){
				var timeRange = global.filterStates.timeQuery;
				var textInput = global.filterStates.textQuery;
				if (timeFilter(currentAlert, timeRange, function(alert){
					return alert.issue_date;
				})){
					return partiallyFilteredArray.push(currentAlert);
				} else {
					return partiallyFilteredArray;
				}
			});

As you can see I'm defining two global environment variables, which are strings that get passed into the filter functions referenced in the require method. However, the browser always throws an error saying global is undefined (when I try to reference the environment variables 'timeQuery' and 'textQuery'). What am I missing here? The examples seem to do exactly this.

**Comment by dcjohnston** [comment]
The npm package is outdated and doesn't include the global var functionality. I solved the issue simply by directly cloning the repo, but it would be nice to update the npm package.

**Comment by Sebmaster** [comment]
@adambom is sadly the only one who can, and he's been MIA for a while.

**Comment by aatifbandey** [comment]
cloned repo but still the same issue
