### ISSUE TITLE
Calculating blocks of array in spawned processes

### ISSUE THREAD

**Issue by robcalcroft** [adambom/parallel.js#113]
I have a dataset that I'm running a calculation on, I'm wanting to use child processes to calculate blocks of the array separately and then combine them. I can't work out the best option to achieve this. I thought using `p.spawn` inside a loop could do it but I was then unsure how to pass the start and end loop variables into the runtime of each spawned process. Can anyone help?

**Comment by Sebmaster** [comment]
You should be able to do .then() on the fresh parallel instance and wrap your array in an object, combining it with start / end props, or alternatively, pass the env option to spawn (only works on the github pulled version though). However .reduce() should actually automatically split your array if it's possible for you to use that, that might make it easier.

**Comment by robcalcroft** [comment]
Do you mean something like:
```javascript
const p = new Parallel({start: 1, stop: 2, data: [[],[],[]]});

p.then(obj => {
    // do calc on obj.data here?
});
```

**Comment by Sebmaster** [comment]
No.

```js
const p = new Parallel(data);

for (let i = 0; i < chunks; ++i) {
  p.then((data) => ({start: chunks * 8, end: (chunks + 1) * 8, data}).spawn(processorFn);
}
```

Note that this would transmit the whole data array to every worker (by stringifying it) so it might be better to slice the array explicitly instead.

**Comment by robcalcroft** [comment]
Right! Gotcha that looks like it'll do the trick, thanks for the help. Will re-open if I need anymore help :smile:

**Comment by robcalcroft** [comment]
How would I go about recombining the data after each process completes, because isn't returning it just gonna overwrite the dataset?

**Comment by Sebmaster** [comment]
Every .then.spawn() will return its own Promise with its own dataset. You'll have to save it in the loop and then recombine when all of them are finished.

(the integrated .reduce might really be easier...)

**Comment by robcalcroft** [comment]
Ahh :confused: how would I use the `reduce` with the dataset? Does it automatically split the dataset?

**Comment by Sebmaster** [comment]
It does. It's limited by the `maxWorkers` option.

**Comment by robcalcroft** [comment]
In a `map` how do I know where I am in the array? E.g. if the sequential version used `i` in a loop to do a calculation, how would I get the equivalent variable `i`?

**Comment by Sebmaster** [comment]
That's not provided with map, you'll have to prepare that in the data yourself or patch the library.

**Comment by robcalcroft** [comment]
So I thought:
```javascript
const p = new Parallel(steps, {
    env: { numSteps, step },
    maxWorkers: 4
});

p.then(steps => ({
    steps,
    iteration: 0
})).map(a => {
    console.log(a.iteration);
});
```
But then this just runs the map only once. Not sure how to keep the iteration cached in the data?

**Comment by Sebmaster** [comment]
.map expects an array. You have to save the iteration in each element.

**Comment by robcalcroft** [comment]
So the data would need to look like `[{step: 0, iteration: 0}, {step: 4, iteration: 1}]`. How would I know the previous state in order to iterate? Sorry if I'm not getting it :confounded:

**Comment by Sebmaster** [comment]
Yes. You can't get the previous state in map. There is no previous step. Everything is in parallel. You map about everything, collect in .then (or .spawn if it's a lot of work) and merge it together.

**Comment by robcalcroft** [comment]
```javascript
import Parallel from 'paralleljs';

const numSteps = 10000000;

const steps = [];

for (let i = 0; i < numSteps; i++) {
    steps.push({step: 0, iteration: i});
}

const p = new Parallel(steps, {
    env: { numSteps }
});

p.map(element => {
    const x = (element.iteration + 0.5) * global.env.step;
    return 4.0 / (1.0 + x * x);
})
.reduce(element => element[0] + element[1])
.then(sum => (1.0 / global.env.numSteps) * sum)
.then(console.log);
```
So I have this, but its crazy slow, is it just the fact that I have 10000000 steps?

**Comment by Sebmaster** [comment]
Yes, you don't do enough work in your handler to make parallel.js worth it in any way. Here's the thing: data transfers are the slow part (especially in the node variant), the less data you need to provide to your worker, the better. The more work you do in your work, the better its efficiency becomes (compared to the data transfer overhead).

**Comment by robcalcroft** [comment]
Ok cool gotcha, thanks

**Comment by robcalcroft** [comment]
Hi again, I've got the syntax working and the parallel working however when I'm console logging, the spawned processes seem to be starting one after another, effectively increasing the runtime by `no. of threads` times. [This](https://github.com/robcalcroft/paralleladventures/blob/master/src/prime-sieve-parallel.js#L92) shows the line where I log the thread start and I get the following result in the console:
```bash
stared thread
stared thread
stared thread
stared thread
664579 primes were found between 0 and 10000000 in 5284 milliseconds
```
The calculation is correct, just the timing seems out.
