### ISSUE TITLE
Resolving Promises Within Workers

### ISSUE THREAD

**Issue by Weblors** [adambom/parallel.js#119]
This is my code:

```javascript
            let p = new Parallel(businessChunks);

            let result = yield p.map(businessIds => {
                'use strict';
                
                const Promise = require('bluebird');
                const BusinessReport = require(process.cwd() + '/bin/dataExport/business');

                return Promise.map(
                    businessIds,
                    businessId => {
                        let businessReport = new BusinessReport(businessId, {
                            qbConnectionString: 'address',
                            botId: 'id'
                        });
                        
                        return businessReport.generate();
                    },
                    {
                        concurrency: process.env.TASK_CONCURRENCY
                    }
                );
            });
```

As you can see, within each worker I'm doing lots of asynchronous stuff using bluebird's promise library and I want the result if that to be returned. But the output gives me four promise objects. How do I get this to work?

**Comment by amilajack** [comment]
This project doesnt really get that much support anymore. I would recommend using another library that does.

**Comment by amilajack** [comment]
Check the graphs:

https://github.com/adambom/parallel.js/graphs/contributors

**Comment by Weblors** [comment]
@amilajack any suggestions?

**Comment by amilajack** [comment]
Good question. Over the past few weeks I've been looking for a WebWorker lib that actually works. About 90% of them don't work properly. I think you should check out:

https://github.com/steelbrain/Worker-Exchange

I personally haven't used it yet but it looks very promising. Tests are at 100% coverage:
https://travis-ci.org/steelbrain/Worker-Exchange

**Comment by amilajack** [comment]
I would also search noms.io for packages. They sort npm repos based on their quality. This project is a rated a 3/100:

<img width="887" alt="screen shot 2016-06-27 at 10 42 06 am" src="https://cloud.githubusercontent.com/assets/6374832/16389735/27b7a328-3c54-11e6-82b4-7c3dd3af49a5.png">

**Comment by Weblors** [comment]
Thanks, mate.
