### ISSUE TITLE
Minified link on Parallel.js homepage returns 404

### ISSUE THREAD

**Issue by ProbonoBonobo** [adambom/parallel.js#120]
[This link](https://raw.githubusercontent.com/adambom/parallel.js/master/lib/parallel.min.js) on the [project homepage](https://adambom.github.io/parallel.js/) doesn't seem to be working for me right now. (D'oh!) No biggie, I'll just get it from NPM, but I thought I'd bring to your attention. Thanks for the cool utility, I'm excited to try it.

**Comment by amilajack** [comment]
This project is pretty much deprecated.

Check the graphs:
https://github.com/adambom/parallel.js/graphs/contributors

**Comment by ProbonoBonobo** [comment]
@amilajack Good call. Are there any libraries you could recommend with a similar feature set? In particular, I'd love to be able to execute map/reduce/filter operations in parallel (when possible).

**Comment by amilajack** [comment]
I would recommend:

https://github.com/steelbrain/Worker-Exchange

I haven't personally used it but its tests are passing.

**Comment by ProbonoBonobo** [comment]
Terrific suggestion. Thanks!
