### ISSUE TITLE
Promise throw safety

### ISSUE THREAD

**Issue by benjamingr** [adambom/parallel.js#67]
Promises/A+ promises are throw safe, which makes them very usable and is a great feature.

```
(...).then(function (data) {
    throw new Error("Hello");
});
```

Does not throw globally, but rather turns the promise into a rejection. Please consider changing the behavior of `.then` in Parallel to be like every other library that supports thenables.

Please see https://github.com/promises-aplus/promises-spec

Thanks a lot and great work so far.

**Comment by Sebmaster** [comment]
Fixed by #85.
