### ISSUE TITLE
Exception handling on threads

### ISSUE THREAD

**Issue by amergin** [adambom/parallel.js#92]
What is the proper way of catching exceptions that may occur inside worker function?

It says [here](http://stackoverflow.com/a/12369185/1467417) that you can listen to the `error` event of the worker - what is the equivalent of this in parallel.js? 

Since parallel.js does supply a `then` function as when dealing with promises, would it make sense the promise to be rejected if one or more of the workers are interrupted by an error? Following in this fashion, the user could supply a `reject` function and a `finally` block as well which is called regardless of the result.

**Comment by code-fury** [comment]
I checked the source code. There is no way to do it unless you hack the src and add error listener to the wrk. This feature should be implemented.

**Comment by amergin** [comment]
Possibly related to https://github.com/adambom/parallel.js/issues/67.

**Comment by Sebmaster** [comment]
Fixed in #85.
