### ISSUE TITLE
Can I pass a function into a spawn?

### ISSUE THREAD

**Issue by shamoons** [adambom/parallel.js#97]
For my array, I have

```
      var neurons = [];

      for (var id = this.list.length - 1; id >= 0; id--) {
        var obj = {
          propagate: this.list[id].propagate,
          target: target[id]
        }

        neurons.push(obj);
      }
```
where `obj.propagate` is a function.

I am then doing
```
      var parallel_neurons = new Parallel(neurons);

      
      var fn = function(a) {
        console.log(a);
      }
      parallel_neurons.spawn(fn);
```

But I only see `target`s from my `log`:

```
[ { target: 0 },
  { target: 0 },
  { target: 1 },
  { target: 0 },
  { target: 0 } ] 
```

Can functions not be passed?

**Comment by Sebmaster** [comment]
No, the object given to the `Parallel` constructor is messaged to the Worker with the [Structured Clone Algorithm](https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/The_structured_clone_algorithm), which doesn't support functions.

**Comment by slfan2013** [comment]
well, I think a basic trick is to use `.toString()` to make the function you want to pass a string object. Put this object in the global environment. In your worker function, use `eval()` to evaluate this function. Then you will be able to use the function in your worker.

see example,

```
    function test(x){
      console.log(x)
    }

    index = Array.apply(null, {length: ooo.e.length}).map(Number.call, Number)
    var p = new Parallel([1,2,3,4,5,6,7],{maxWorkers:1000000,
    env: {
      test:test.toString()
      }})
p.map(function (d) {
  console.log(global.env.test)
  eval(global.env.test)
  console.log(test)
  test(10)
});
```
